//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Counter(

	input 			          		MAX10_CLK1_50,

	//////////// KEY //////////
	input 		     [1:0] 		KEY,

	//////////// LED //////////
	output 		     [9:0] 		LEDR,

	//////////// SW //////////
	input 		     [9:0] 		SW
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

	 wire reset1;
	 wire load1; 
	 wire up_down1;
    wire [3:0] data_in1;
    wire [3:0] count1;
	 wire clk_1hz;
	 
	 assign reset1 = KEY[0];
	 assign up_down1 = KEY[1];
	 assign data_in1 = SW[3:0];
	 assign load1 = SW[9];
	 assign LEDR[3:0] = count1;
	 
    //(clk,reset,div_num, clk_out);		
	 //clk_div_n CLK1 (.clk_in(MAX10_CLK1_50), .reset(reset1), .div_num(50000000), .clk_out(clk_1Hz));
	 clockDivider CD1 (.clk_in(MAX10_CLK1_50), .clk_out(clk_1hz));
	 UpDownCounter UD1 (.clk(clk_1Hz), .reset(reset1), .load(load1), .up_down(up_down1), .data_in(data_in1), .count(count1));

endmodule
